services:
  esperanza:
    image: esperanza
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
  tts-service:
    build: ./coqui-ai-tts
    ports:
      - "5002:5002"

  whisper-service:
    build: ./whisper
    ports:
      - "8080:8080"